# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build First job
  - job: SecondJob
    steps:
      - bash: echo Second Job
- stage: DevDeploy
  dependsOn: Build
  jobs:
  - job: DevDeployJob
    steps:
    - bash: echo DevDeploy job

- stage: QADeploy
  dependsOn: Build
  jobs:
  - job: QADeployJob
    steps:
    - bash: echo QADeploy job

- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs:
  - job: ProdJob
    steps:
    - bash: echo ProdDeploy job

